# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: 'DeployMonitoring'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: AzureResourceGroupDeployment@2
    displayName: 'Provision Web Ping Test'
    inputs:
      ConnectedServiceName: 'DCD-CFT-Sandbox'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'rdo-perftest-poc'
      location: 'UK South'
      csmFile: 'app_ins_alerts.json'
      csmParametersFile: 'app_ins_alerts.parameters.json'
      deploymentMode: Incremental